name: Refresh ASN data

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Run build
        run: bun build.js

      - name: Commit and push
        run: |
          git config user.email "70700766+tiagozip@users.noreply.github.com"
          git config user.name "tiagobot"
          git add asn/ logos/ last_run.txt
          git diff --staged --quiet || git commit -m "build $(date -u +%Y-%m-%d)"
          git push